name: Build

on:
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/build.yml
      - "*.Dockerfile"
  push:
    branches: [main]
    paths:
      - .github/workflows/build.yml
      - "*.Dockerfile"
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

env:
  # renovate: datasource=github-releases depName=hadolint/hadolint
  HADOLINT_VERSION: v2.12.0

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        image:
          - file: alpine-devcontainer
            name: devc/alpine
            registry:
              host: rg.fr-par.scw.cloud
              username: nologin
              password: SCW_SECRET_KEY
          - file: alpine-devcontainer
            name: ${{ github.repository_owner }}/alpine-devcontainer
            registry:
              host: ghcr.io
              username: nikaro
              password: GITHUB_TOKEN
    steps:
      - name: Checkout repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Install hadolint
        uses: jaxxstorm/action-install-gh-release@c5ead9a448b4660cf1e7866ee22e4dc56538031a # v1.10.0
        with:
          repo: hadolint/hadolint
          tag: ${{ env.HADOLINT_VERSION }}
          cache: enable
          extension-matching: disable
          rename-to: hadolint
          chmod: 0755

      - name: Run pre-commit hooks
        uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507 # v3.0.0

      - name: Setup QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0

      - name: Setup Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Login to registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ matrix.image.registry.host }}
          username: ${{ matrix.image.registry.username }}
          password: ${{ secrets[matrix.image.registry.password] }}

      - name: Build and push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          file: ./${{ matrix.image.file }}.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref_name == 'main' }}
          tags: ${{ matrix.image.registry.host }}/${{ matrix.image.name }}:latest
