name: Build

on:
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/build.yml
      - '*.Dockerfile'
  push:
    branches: [main]
    paths:
      - .github/workflows/build.yml
      - '*.Dockerfile'
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        image:
          - file: alpine-devcontainer
            name: devc/alpine
            registry:
              host: rg.fr-par.scw.cloud
              username: nologin
              password: ${{ secrets.SCW_SECRET_KEY }}
          - file: alpine-devcontainer
            name: ${{ github.repository_owner }}/alpine-devcontainer
            registry:
              host: ghcr.io
              username: ${{ github.repository_owner }}
              password: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Install hadolint
        uses: jaxxstorm/action-install-gh-release@c5ead9a448b4660cf1e7866ee22e4dc56538031a # v1.10.0
        with:
          repo: hadolint/hadolint
          tag: v2.12.0
          cache: enable
          extension-matching: disable
          rename-to: hadolint
          chmod: 0755

      - name: Run pre-commit hooks
        uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507 # v3.0.0

      - name: Setup QEMU
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2.2.0

      - name: Setup Buildx
        uses: docker/setup-buildx-action@4c0219f9ac95b02789c1075625400b2acbff50b1 # v2.9.1

      - name: Login to registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          registry: ${{ matrix.image.registry.host }}
          username: ${{ matrix.image.registry.username }}
          password: ${{ matrix.image.registry.password }}

      - name: Build and push
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # v4.1.1
        with:
          context: .
          file: ./${{ matrix.image.file }}.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref_name == 'main' }}
          tags: ${{ matrix.image.registry.host }}/${{ matrix.image.name }}:latest
