name: Build

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

env:
  # renovate: datasource=github-releases depName=hadolint/hadolint
  HADOLINT_VERSION: v2.12.0

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Install hadolint
        uses: jaxxstorm/action-install-gh-release@71d17cb091aa850acb2a1a4cf87258d183eb941b # v1.11.0
        with:
          repo: hadolint/hadolint
          tag: ${{ env.HADOLINT_VERSION }}
          cache: enable
          extension-matching: disable
          rename-to: hadolint
          chmod: 0755

      - name: Run pre-commit hooks
        uses: nikaro/actions/pre-commit@fdbf26a2c9512b5e617ae65fa77a3f92c1598a56 # 1.3.21

  build:
    name: Build
    needs: [lint]
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        image:
          - file: alpine-devcontainer
            name: ${{ github.repository_owner }}/alpine-devcontainer
            registry:
              host: ghcr.io
              username: nikaro
              password: GITHUB_TOKEN
          - file: debian-devcontainer
            name: ${{ github.repository_owner }}/debian-devcontainer
            registry:
              host: ghcr.io
              username: nikaro
              password: GITHUB_TOKEN
          - file: pulumi-executor
            name: ${{ github.repository_owner }}/pulumi-executor
            registry:
              host: ghcr.io
              username: nikaro
              password: GITHUB_TOKEN
          - file: wait-for-it
            name: ${{ github.repository_owner }}/wait-for-it
            registry:
              host: ghcr.io
              username: nikaro
              password: GITHUB_TOKEN
          - file: wolfi-devcontainer
            name: ${{ github.repository_owner }}/wolfi-devcontainer
            registry:
              host: ghcr.io
              username: nikaro
              password: GITHUB_TOKEN
    steps:
      - name: Checkout repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0

      - name: Setup Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0

      - name: Login to registry
        if: github.ref_name == 'main'
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        with:
          registry: ${{ matrix.image.registry.host }}
          username: ${{ matrix.image.registry.username }}
          password: ${{ secrets[matrix.image.registry.password] }}

      - name: Build and push
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        with:
          context: .
          file: ./${{ matrix.image.file }}.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref_name == 'main' }}
          tags: ${{ matrix.image.registry.host }}/${{ matrix.image.name }}:latest
