name: Build

on:
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/build.yml
      - '*.Dockerfile'
  push:
    branches: [ main ]
    paths:
      - .github/workflows/build.yml
      - '*.Dockerfile'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        image:
          - alpine-devcontainer
    steps:

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          dockerfile: ./${{ matrix.image }}.Dockerfile
      - uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2.2.0
      - uses: docker/setup-buildx-action@2a1a44ac4aa01993040736bd95bb470da1a38365 # v2.9.0
      - uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # v4.1.1
        with:
          context: .
          file: ./${{ matrix.image }}.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref_name == 'main' }}
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:latest
