name: Build

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * 3"
  workflow_dispatch:

env:
  TASK_X_REMOTE_TASKFILES: 1

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Configure environment for brew
        shell: bash
        run: |
          {
            echo "HOMEBREW_PREFIX=/home/linuxbrew/.linuxbrew";
            echo "HOMEBREW_CELLAR=/home/linuxbrew/.linuxbrew/Cellar";
            echo "HOMEBREW_REPOSITORY=/home/linuxbrew/.linuxbrew/Homebrew";
          } >> "$GITHUB_ENV"
          {
            echo "/home/linuxbrew/.linuxbrew/sbin";
            echo "/home/linuxbrew/.linuxbrew/bin";
          } >> "$GITHUB_PATH"

      - name: Install tools
        shell: bash
        run: |-
          brew install \
            actionlint \
            check-jsonschema \
            fd \
            go-task \
            hadolint \
            jq \
            prettier \
            shellcheck \
            shfmt \
            yamlfmt \
            yamllint \

      - name: Lint
        run: task lint --yes

  build:
    name: Build
    needs: [lint]
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        image:
          - name: alpine-devcontainer
            platforms: linux/amd64,linux/arm64
          - name: debian-devcontainer
            platforms: linux/amd64,linux/arm64
          - name: gha
            platforms: linux/amd64
          - name: wait-for-it
            platforms: linux/amd64,linux/arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Setup QEMU
        uses: docker/setup-qemu-action@master

      - name: Setup Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to registry
        if: github.ref_name == 'main'
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@master
        with:
          context: .
          file: ./${{ matrix.image.name }}.Dockerfile
          platforms: ${{ matrix.image.platforms }}
          push: ${{ github.ref_name == 'main' }}
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }}:latest
