---
name: Build

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * 3"
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Install hadolint
        uses: jaxxstorm/action-install-gh-release@25d5e2dd555cd74f1fab9ac1e6ea117acde2c0c4 # v1.12.0
        with:
          repo: hadolint/hadolint
          cache: enable
          extension-matching: disable
          rename-to: hadolint
          chmod: 0755

      - name: Run pre-commit hooks
        uses: nikaro/actions/pre-commit@main
        with:
          python-version: 3.x

  build:
    name: Build
    needs: [lint]
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        image:
          - name: alpine-devcontainer
          - name: debian-devcontainer
          - name: wait-for-it
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Setup QEMU
        uses: docker/setup-qemu-action@main

      - name: Setup Buildx
        uses: docker/setup-buildx-action@main

      - name: Login to registry
        if: github.ref_name == 'main'
        uses: docker/login-action@main
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@main
        with:
          context: .
          file: ./${{ matrix.image.name }}.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref_name == 'main' }}
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }}:latest
